blank_issues_enabled: false
contact_links:
  - name: ğŸ’¡ Feature Request
    url: https://github.com/kilohealth/rn-fitness-tracker/discussions/new?category=ideas
    about: Share ideas for new features.
  - name: â“ Ask a Question
    url: https://github.com/kilohealth/rn-fitness-tracker/discussions/new?category=q-a
    about: Ask the community for help.
  - name: ğŸ™Œ Show and tell
    url: https://github.com/kilohealth/rn-fitness-tracker/discussions/new?category=show-and-tell
    about: Share what you've built with React Native Fitness Tracker.
